---
sidebar: sidebar 
permalink: concept-azure-netapp-files.html 
keywords: azure netapp files, cost, price, features, azure netapp files features, anf, supported regions, azure regions, azure netapp files regions 
summary: Azure NetApp Files 사용하면 기업은 클라우드에 맞게 리팩토링할 필요 없이 성능 집약적이고 대기 시간에 민감한 핵심 비즈니스 핵심 애플리케이션을 Azure로 마이그레이션하고 실행할 수 있습니다. 
---
= Azure NetApp Files 에 대해 알아보기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Azure NetApp Files 사용하면 기업은 클라우드에 맞게 리팩토링할 필요 없이 성능 집약적이고 대기 시간에 민감한 핵심 비즈니스 핵심 애플리케이션을 Azure로 마이그레이션하고 실행할 수 있습니다.



== 특징

* 여러 프로토콜을 지원하므로 Linux 및 Windows 애플리케이션을 Azure에서 원활하게 "리프트 앤 시프트" 방식으로 실행할 수 있습니다.
* 다양한 성능 계층을 통해 워크로드 성능 요구 사항에 맞춰 긴밀하게 조정할 수 있습니다.
* SAP HANA, GDPR, HIPAA를 포함한 주요 인증을 통해 가장 까다로운 작업 부하도 Azure로 마이그레이션할 수 있습니다.




=== NetApp Console 의 추가 기능

* NetApp Console 에서 직접 NFS 또는 SMB 데이터를 Azure NetApp Files 로 마이그레이션합니다.  데이터 마이그레이션은 NetApp Copy and Sync 통해 지원됩니다.
+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["복사 및 동기화에 대해 자세히 알아보세요"^]

* 인공 지능(AI) 기반 기술을 사용하는 NetApp Data Classification 데이터 컨텍스트를 이해하고 Azure NetApp Files 계정에 있는 중요한 데이터를 식별하는 데 도움이 될 수 있습니다.
+
https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["데이터 분류에 대해 자세히 알아보세요"^]





== NetApp Console

Azure NetApp Files NetApp Console 통해 액세스할 수 있습니다.

NetApp Console 엔터프라이즈급 온프레미스 및 클라우드 환경 전반에서 NetApp 스토리지 및 데이터 서비스를 중앙에서 관리할 수 있는 기능을 제공합니다. NetApp 데이터 서비스에 액세스하고 사용하려면 콘솔이 필요합니다. 관리 인터페이스로서, 하나의 인터페이스에서 여러 스토리지 리소스를 관리할 수 있습니다. 콘솔 관리자는 기업 내 모든 시스템의 저장소와 서비스에 대한 액세스를 제어할 수 있습니다.

NetApp Console 사용하려면 라이선스나 구독이 필요하지 않으며, 스토리지 시스템이나 NetApp 데이터 서비스에 대한 연결을 보장하기 위해 클라우드에 Console 에이전트를 배포해야 할 때만 요금이 부과됩니다. 그러나 콘솔에서 액세스할 수 있는 일부 NetApp 데이터 서비스는 라이선스 기반이거나 구독 기반입니다.

자세히 알아보세요link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp Console"^] .



== 비용

https://azure.microsoft.com/pricing/details/netapp/["Azure NetApp Files 가격 보기"^]

구독 및 청구는 콘솔이 아닌 Azure NetApp Files 서비스에서 유지 관리됩니다.



== 지원되는 지역

https://bluexp.netapp.com/cloud-volumes-global-regions["지원되는 Azure 지역 보기"^]



== 도움 받기

Azure NetApp Files 와 관련된 기술 지원 문제의 경우 Azure Portal을 사용하여 Microsoft에 지원 요청을 기록하세요.  연결된 Microsoft 구독을 선택하고 *저장소* 아래에서 * Azure NetApp Files* 서비스 이름을 선택합니다.  Microsoft 지원 요청을 만드는 데 필요한 나머지 정보를 제공하세요.



== 관련 링크

* link:https://bluexp.netapp.com/azure-netapp-files["NetApp Console 웹사이트: Azure NetApp Files"^]
* link:https://learn.microsoft.com/azure/azure-netapp-files/["Azure NetApp Files 설명서"^]
* link:https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["복사 및 동기화 설명서"^]

